### ISSUE TITLE
Python 3.10 / Jinja issue?

### ISSUE THREAD

**Issue by rduivenvoorde** [AirBreak-UIA/SensorThingsAPI_QGIS-plugin#2]
After earlier succesfully testing the plugin, I now get:

```
Couldn't load plugin 'SensorThingsAPI' due to an error when calling its classFactory() method 

ImportError: cannot import name 'soft_unicode' from 'markupsafe' (/usr/lib/python3/dist-packages/markupsafe/__init__.py) 
Traceback (most recent call last):
  File "/home/richard/bin/qgis_/master/debug/share/qgis/python/qgis/utils.py", line 423, in _startPlugin
    plugins[packageName] = package.classFactory(iface)
  File "/home/richard/.local/share/QGIS/QGIS3/profiles/default/python/plugins/SensorThingsAPI/__init__.py", line 26, in classFactory
    from SensorThingsAPI.sensor_things import SensorThingsPlugin
  File "/home/richard/bin/qgis_/master/debug/share/qgis/python/qgis/utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/home/richard/.local/share/QGIS/QGIS3/profiles/default/python/plugins/SensorThingsAPI/sensor_things.py", line 39, in 
    from SensorThingsAPI.sensor_things_location_dlg import SensorThingsLocationDialog
  File "/home/richard/bin/qgis_/master/debug/share/qgis/python/qgis/utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/home/richard/.local/share/QGIS/QGIS3/profiles/default/python/plugins/SensorThingsAPI/sensor_things_location_dlg.py", line 36, in 
    from SensorThingsAPI.html.generate import htmlUtil
  File "/home/richard/bin/qgis_/master/debug/share/qgis/python/qgis/utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/home/richard/.local/share/QGIS/QGIS3/profiles/default/python/plugins/SensorThingsAPI/html/generate.py", line 30, in 
    from jinja2 import Environment, FileSystemLoader
  File "/home/richard/bin/qgis_/master/debug/share/qgis/python/qgis/utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/home/richard/.local/lib/python3.10/site-packages/jinja2/__init__.py", line 12, in 
    from .environment import Environment
  File "/home/richard/bin/qgis_/master/debug/share/qgis/python/qgis/utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/home/richard/.local/lib/python3.10/site-packages/jinja2/environment.py", line 25, in 
    from .defaults import BLOCK_END_STRING
  File "/home/richard/bin/qgis_/master/debug/share/qgis/python/qgis/utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/home/richard/.local/lib/python3.10/site-packages/jinja2/defaults.py", line 3, in 
    from .filters import FILTERS as DEFAULT_FILTERS  # noqa: F401
  File "/home/richard/bin/qgis_/master/debug/share/qgis/python/qgis/utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/home/richard/.local/lib/python3.10/site-packages/jinja2/filters.py", line 13, in 
    from markupsafe import soft_unicode
ImportError: cannot import name 'soft_unicode' from 'markupsafe' (/usr/lib/python3/dist-packages/markupsafe/__init__.py)
```

I think(!) it has something todo with using an older Jinja version in combination with Python 3.10

QGIS MetaSearch plugin had/has the same issue in the Flatpak QGIS package:
https://github.com/flathub/org.qgis.qgis/issues/174

**Comment by rduivenvoorde** [comment]
Sorry, closing. Was my own setup, holding an older version of Jinja2 (as dependency for older module).
